### ISSUE TITLE
nao fonciona

### ISSUE THREAD

**Issue by alienwarework** [SandroMiguel/public-chat#1]
Ola, estou a testar este sciript mas como posso testar se nao tem uma tabela users, na base de dados, oara poder criar o nickname?

**Comment by SandroMiguel** [comment]
Olá! Existe um tutorial completo em [https://www.revista-programar.info/artigos/sistema-de-chat-publico-em-php/](https://www.revista-programar.info/artigos/sistema-de-chat-publico-em-php/)
